import type { ThemeConfig } from "darkraise-ui/theme"

// ghr has one look: ghr-theme.css overrides the palette the engine derives,
// and the only choice left to the viewer is the colour mode.
export const themeConfig: ThemeConfig = {
  defaults: {
    accentColor: "blue",
    surfaceColor: "slate",
    preset: "default",
    backgroundStyle: "solid",
    backgroundIntensity: "balanced",
    gradientPattern: "blobs",
    mode: "dark",
    density: "compact",
    elevation: "low",
    buttonElevation: "flat",
    surfaceIntensity: "balanced",
    radius: "subtle",
    controlDepth: "flush",
    shellStyle: "classic",
    sidebarActiveBar: "ring",
    fontSize: "medium",
    accentIntensity: "balanced",
    outerGlow: "none",
    innerGlow: "none",
  },
  switcher: {
    enabled: false,
    axes: {
      mode: false,
      accentColor: false,
      surfaceColor: false,
      preset: false,
      backgroundStyle: false,
      backgroundIntensity: false,
      gradientPattern: false,
      density: false,
      elevation: false,
      buttonElevation: false,
      surfaceIntensity: false,
      radius: false,
      controlDepth: false,
      shellStyle: false,
      sidebarActiveBar: false,
      fontSize: false,
      accentIntensity: false,
      outerGlow: false,
      innerGlow: false,
      presetAxes: false,
    },
  },
}
